# Etapa 1: Build da aplicação
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app

# Copia o projeto
COPY pom.xml .
COPY src ./src

# Executa o build
RUN mvn package -DskipTests

# Etapa 2: Imagem de runtime leve
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Copia apenas o necessário do build
COPY --from=build /app/target/quarkus-app/ ./

# Define o comando para rodar o app
CMD ["java", "-jar", "quarkus-run.jar"]
