version: '3'

services:
  postgres:
    build:
      context: ./postgresql
      dockerfile: Dockerfile
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - beeshortener

  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.legacy-jar
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - beeshortener

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - beeshortener
    ports:
      - "3000:3000"

volumes:
  pgdata:

networks:
  beeshortener:
    driver: bridge