services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: beetech
      MARIADB_DATABASE: beeshortener
      MARIADB_USER: beetech
      MARIADB_PASSWORD: beetech
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
    networks:
      - beeshortener

  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - mariadb
    networks:
      - beeshortener

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
    env_file: .env
    networks:
      - beeshortener

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mariadb
      - backend
      - frontend
    networks:
      - beeshortener

volumes:
  mariadb_data:

networks:
  beeshortener:
    driver: bridge